### ISSUE TITLE
Error trying to change colors

### ISSUE THREAD

**Issue by cjdduarte** [iamjustkoi/StudyTimeStats#12]
**Bug/Issue Description**
Error trying to change colors

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-26 06:58:09

Caught exception:
Traceback (most recent call last):
  File "D:\Anki\Anki.2.1.data\addons21\1247171202\src\options.py", line 223, in accept
    self._save()
  File "D:\Anki\Anki.2.1.data\addons21\1247171202\src\options.py", line 171, in _save
    self.manager.write_config()
  File "D:\Anki\Anki.2.1.data\addons21\1247171202\src\config.py", line 44, in write_config
    self.mw.addonManager.writeAddonMeta(self._addon, self._meta)
  File "aqt.addons", line 303, in writeAddonMeta
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anki\\Anki\\meta.json'

**Comment by iamjustkoi** [comment]
Should be fixed with the most recent release! Sorry about that!
