### ISSUE TITLE
Crashes when trying to open Options

### ISSUE THREAD

**Issue by GreginUdora** [iamjustkoi/StudyTimeStats#15]
**Bug/Issue Description**
The Plugin crashes whe I try to open the options menu.

Debuginformationen:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2022-11-29 08:39:02

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1247171202\src\main.py", line 84, in on_options_called
    dialog = TimeStatsOptionsDialog(get_config_manager())
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1247171202\src\options.py", line 112, in __init__
    self._load()
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1247171202\src\options.py", line 201, in _load
    self._load_excluded_decks()
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1247171202\src\options.py", line 248, in _load_excluded_decks
    for deck in self.manager.mw.col.decks.all_names_and_ids():
AttributeError: 'DeckManager' object has no attribute 'all_names_and_ids'

**Comment by iamjustkoi** [comment]
Ope, makes sense, thanks for the report! Will try and push out a fix for this as soon as I can.

**Comment by GreginUdora** [comment]
Thank You :)

**Comment by iamjustkoi** [comment]
> Thank You :)

Anytime! :D

Should be fixed in the most recent release! Wish you the best!
