### ISSUE TITLE
Error on Settings Menu Open

### ISSUE THREAD

**Issue by JeremiaWilliams** [iamjustkoi/StudyTimeStats#20]
**Bug/Issue Description**
An error message appears when going to the settings menu.

**To Reproduce**
Using Anki 2.1.60-2.1.64 on Apple Silicon,
1. Go to 'Tools'
2. Click on 'Study Time Stats Options'

**System/Debug Info**
```
Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-05-26 09:22:26
Add-ons possibly involved: ⁨Study Time Stats⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/ /Library/Application Support/Anki2/addons21/1247171202/src/toolbar.py", line 44, in on_options_called
    dialog = TimeStatsOptionsDialog(TimeStatsConfigManager(mw))
  File "/Users/ /Library/Application Support/Anki2/addons21/1247171202/src/options.py", line 174, in __init__
    self._load()
  File "/Users/ /Library/Application Support/Anki2/addons21/1247171202/src/options.py", line 282, in _load
    _add_cell_to_list(self.ui.cellListWidget, CellItem(self.ui.cellListWidget, is_empty=True))
  File "/Users/ /Library/Application Support/Anki2/addons21/1247171202/src/options.py", line 583, in __init__
    self.widget.setupUi(CellWidget=self)
  File "/Users/ /Library/Application Support/Anki2/addons21/1247171202/res/ui/cell_item.py", line 99, in setupUi
    self.dragHandle.setIcon(icon1)
  File "/Users/ /Library/Application Support/Anki2/addons21/1247171202/res/ui/forms.py", line 139, in setIcon
    mask = pixmap.createMaskFromColor(QColor('black'), Qt.MaskOutColor)
  File "aqt.qt.qt5_compat", line 353, in __getattr__
AttributeError: type object 'Qt' has no attribute 'MaskOutColor'
```

**Comment by iamjustkoi** [comment]
Yep, sorry about that, caught this just a bit ago. 
Should be fixed in the most recent release (v2.0.2)!
