### ISSUE TITLE
Add on throws error upon staring anki

### ISSUE THREAD

**Issue by ChrolloRifat** [iamjustkoi/StudyTimeStats#45]
**Bug/Issue Description**
A short description of the issue.
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.6.7-arch1-1-x86_64-with-glibc2.38

When loading Study Time Stats:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/home/rif/.local/share/Anki2/addons21/1247171202/__init__.py", line 8, in <module>
    from .src import toolbar
  File "/home/rif/.local/share/Anki2/addons21/1247171202/src/toolbar.py", line 12, in <module>
    from .options import TimeStatsOptionsDialog
  File "/home/rif/.local/share/Anki2/addons21/1247171202/src/options.py", line 41, in <module>
    from ..res.ui.cell_item import Ui_CellWidget
  File "/home/rif/.local/share/Anki2/addons21/1247171202/res/ui/cell_item.py", line 11, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**To Reproduce**
Steps to reproduce:

**Screenshots/Visuals**
If necessary/applicable, add some screenshots to help explain the issue.

**System/Debug Info**
You can get this from Anki in Help -> About -> Copy Debug Info,

**Additional Context**
Any other context that might seem important.

**Comment by iamjustkoi** [comment]
Should be fixed in the most recent release (v2.1.0), hopefully! Will have to see.

Thanks for reporting!
