### ISSUE TITLE
Error on startup for Qt5/macOS versions of Anki

### ISSUE THREAD

**Issue by iamjustkoi** [iamjustkoi/StudyTimeStats#48]
**Bug/Issue Description**
A short description of the issue.

**To Reproduce**
Steps to reproduce:
1. Open Anki
2. Error dialog pops up on screen

**System/Debug Info**
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-14.0-x86_64-i386-64bit

When loading Study Time Stats:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/alexkotusenko/Library/Application Support/Anki2/addons21/1247171202/__init__.py", line 8, in <module>
    from .src import toolbar
  File "/Users/alexkotusenko/Library/Application Support/Anki2/addons21/1247171202/src/toolbar.py", line 12, in <module>
    from .options import TimeStatsOptionsDialog
  File "/Users/alexkotusenko/Library/Application Support/Anki2/addons21/1247171202/src/options.py", line 55, in <module>
    from ..res.ui.Qt5.options_dialog import Ui_OptionsDialog
  File "/Users/alexkotusenko/Library/Application Support/Anki2/addons21/1247171202/res/ui/Qt5/options_dialog.py", line 405, in <module>
    from res.ui.forms import HoverButton
ModuleNotFoundError: No module named 'res'

**Additional Context**
Reported by another user in messages, moved here for better tracking.

**Comment by iamjustkoi** [comment]
Quick fix in the most recent patch (v2.1.3)!
