### ISSUE TITLE
An add-on you installed failed to load.

### ISSUE THREAD

**Issue by Crostiini** [iamjustkoi/StudyTimeStats#6]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Study Time Stats⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\xelak\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 314, in <module>
    initialize()
  File "C:\Users\xelak\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 63, in initialize
    build_hooks()
  File "C:\Users\xelak\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 72, in build_hooks
    gui_hooks.webview_did_inject_style_into_page.append(format_congrats)
AttributeError: module 'aqt.gui_hooks' has no attribute 'webview_did_inject_style_into_page'

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-03 11:11:09

Traceback (most recent call last):
  File "aqt\main.py", line 521, in loadCollection
  File "aqt\main.py", line 661, in moveToState
  File "aqt\main.py", line 668, in _deckBrowserState
  File "aqt\deckbrowser.py", line 58, in show
  File "aqt\deckbrowser.py", line 115, in _renderPage
  File "aqt\deckbrowser.py", line 125, in __renderPage
  File "aqt\webview.py", line 378, in stdHtml
  File "aqt\gui_hooks.py", line 3024, in __call__
  File "C:\Users\xelak\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 128, in format_webview
    content.body += formatted_html()
  File "C:\Users\xelak\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 226, in formatted_html
    total_hrs, ranged_hrs, days_ago = get_review_stats()
  File "C:\Users\xelak\AppData\Roaming\Anki2\addons21\1247171202\__init__.py", line 178, in get_review_stats
    dids = mw.col.decks.all_ids()
AttributeError: 'DeckManager' object has no attribute 'all_ids'

**Comment by iamjustkoi** [comment]
Scheduled this for the next update. Thanks for reporting!
